spring.datasource.url=jdbc:postgresql://localhost:5432/employees-db
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.username=ouassima
spring.datasource.password=ouassima
server.port=8081
